name: Sync Fork

on:
  schedule:
    - cron: '0 1 * * *' # every day at 1 AM
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: zsa
          base: firmware20
          head: firmware20
